services:

  mysql:
    image: mysql:8.0
    container_name: ors-mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: ors10
      MYSQL_USER: root
      MYSQL_PASSWORD: root@123
      ports:
      - "3308:3306"
    networks:
      - ors_network
      TZ: Asia/Kolkata
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5

  backend:
    build:
      context: .              # ✅ Project_10 folder
      dockerfile: dockerfile  # ✅ same folder ka Dockerfile
    container_name: ors-backend
    restart: always
    depends_on:
      mysql:
        condition: service_healthy
    ports:
      - "8084:8084"

volumes:
  mysql_data:
