services:

  mysql:
    image: mysql:8.0
    container_name: ors-mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: ors10
      TZ: Asia/Kolkata
    ports:
      - "3308:3306"   # ðŸ‘‰ tum manually MySQL connect kar sako
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - ors_network

  backend:
    build:
      context: .
      dockerfile: dockerfile
    container_name: ors-backend
    restart: always
    ports:
      - "8084:8084"
    networks:
      - ors_network

volumes:
  mysql_data:

networks:
  ors_network:
    driver: bridge
